apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: express-msvc:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Never